//img
import image0 from "../images/products/apliques-de-pared/duplo-negro.jpg"
import image1 from "../images/products/apliques-de-pared/iria.jpg"
import image2 from "../images/products/apliques-de-pared/lenis.jpg"
import image3 from "../images/products/apliques-de-pared/licelot.jpg"
import image4 from "../images/products/apliques-de-pared/queen.jpg"
import image5 from "../images/products/cabezales/falco.jpg"
import image6 from "../images/products/cabezales/guardare.jpg"
import image7 from "../images/products/cabezales/look-mod.jpg"
import image8 from "../images/products/cabezales/pesca-blanco.jpg"
import image9 from "../images/products/farolas/atlantis.jpg"
import image10 from "../images/products/farolas/bollard.jpg"
import image11 from "../images/products/farolas/perla.jpg"
import image12 from "../images/products/farolas/vela.jpg"
import image13 from "../images/products/industriales/dooku.jpg"
import image14 from "../images/products/industriales/mare-led-blanco.jpg"
import image15 from "../images/products/industriales/ufo.jpg"
import image16 from "../images/products/lineales/Tasso-asimetrico.jpg"
import image17 from "../images/products/lineales/Tasso-mezzi-led.jpg"
import image18 from "../images/products/lineales/tasso-square.jpg"
import image19 from "../images/products/spots-empotrables/cobo.jpg"
import image20 from "../images/products/spots-empotrables/gala.jpg"
import image21 from "../images/products/spots-empotrables/okkyo.jpg"
import image22 from "../images/products/spots-empotrables/shine.jpg"
import image23 from "../images/products/spots-empotrables/still.jpg"
import image24 from "../images/products/tiras-led/cintas-led.jpg"
import image25 from "../images/products/tiras-led/neon jackie.jpg"
export const JsonData = [
    {
        id: 1,
        title: " Duplo Negro",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "aplidpared",
        thumbnail:"...",
        images: image0,
    },
    {
        id: 2,
        title: "Iria",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "aplidpared",
        thumbnail: "...",
        images: image1,
    },
    {
        id: 3,
        title: "Lenis",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "aplidpared",
        thumbnail: "...",
        images: image2,
    },
    {
        id: 4,
        title: " Licelot",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "aplidpared",
        thumbnail:"...",
        images: image3,
    },
    {
        id: 5,
        title: "Queen",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "aplidpared",
        thumbnail: "...",
        images: image4,
    },
    {
        id: 6,
        title: "Falco",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "cabezales",
        thumbnail: "...",
        images: image5,
    },
    {
        id: 7,
        title: " Guardare",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "cabezales",
        thumbnail:"...",
        images: image6,
    },
    {
        id: 8,
        title: "Look Mod",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "cabezales",
        thumbnail: "...",
        images: image7,
    },
    {
        id: 9,
        title: "Pesca Blanco",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "cabezales",
        thumbnail: "...",
        images: image8,
    },
    {
        id: 10,
        title: " Atlantis",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "farolas",
        thumbnail:"...",
        images: image9,
    },
    {
        id: 11,
        title: "Bollard",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "farolas",
        thumbnail: "...",
        images: image10,
    },
    {
        id: 12,
        title: "Perla",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "farolas",
        thumbnail: "...",
        images: image11,
    },
    {
        id: 13,
        title: " Vela",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "farolas",
        thumbnail:"...",
        images: image12,
    },
    {
        id: 14,
        title: "Dooku",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "industriales",
        thumbnail: "...",
        images: image13,
    },
    {
        id: 15,
        title: "Mare Led Blanco",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "industriales",
        thumbnail: "...",
        images: image14,
    },
    {
        id: 16,
        title: "Ufo",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "industriales",
        thumbnail: "...",
        images: image15,
    },
    {
        id: 17,
        title: "Tasso Asimetrico",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "lineales",
        thumbnail: "...",
        images: image16,
    },
    {
        id: 18,
        title: "Tasso Mezzi Led",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "lineales",
        thumbnail: "...",
        images: image17,
    },
    {
        id: 19,
        title: "Tasso Square",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "lineales",
        thumbnail: "...",
        images: image18,
    },
    {
        id: 20,
        title: "Cobo",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "empotrables",
        thumbnail: "...",
        images: image19,
    },
    {
        id: 21,
        title: "Gala",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "empotrables",
        thumbnail: "...",
        images: image20,
    },
    {
        id: 22,
        title: "Okkyo",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "empotrables",
        thumbnail: "...",
        images: image21,
    },
    {
        id: 23,
        title: "Shine",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "empotrables",
        thumbnail: "...",
        images: image22,
    },
    {
        id: 24,
        title: "Still",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "empotrables",
        thumbnail: "...",
        images: image23,
    },
    {
        id: 25,
        title: "Cintas Led",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "cintas-led",
        thumbnail: "...",
        images: image24,
    },
    {
        id: 26,
        title: "Neon Jackie",
        description: "Descripcion",
        price: 1000,
        discountPercentage: 12.96,
        rating: 4.69,
        stock: 94,
        brand: "Apple",
        category: "cintas-led",
        thumbnail: "...",
        images: image25,
    }
]